/**
 * NQ Collection — Seed Script
 * ────────────────────────────
 * Populates the database with categories, products and sample reviews.
 * Safe to re-run — skips anything that already exists.
 *
 * Usage:
 *   cd backend
 *   node seeders/seed.js
 */

require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('../models/Category');
const Product  = require('../models/Product');
const User     = require('../models/User');

// ── Unsplash image helper ────────────────────────────────────────────────────
const img = (id, w = 800, h = 1000) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format&q=80`;

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ MongoDB connected\n');

  // ── Categories ──────────────────────────────────────────────────────────────
  console.log('Seeding categories...');

  const catData = [
    {
      name: 'Wigs',
      description: 'Premium quality wigs — straight, curly, lace front, HD lace & more',
      sortOrder: 1,
      isActive: true,
      metaTitle: 'Premium Wigs in Cameroon — NQ Collection',
      metaDescription: 'Shop high-quality wigs in Cameroon. Lace fronts, straight, curly, body wave. Fast delivery.',
    },
    {
      name: 'Bags',
      description: 'Classy designer-inspired bags for every occasion',
      sortOrder: 2,
      isActive: true,
      metaTitle: 'Luxury Bags in Cameroon — NQ Collection',
      metaDescription: 'Shop elegant handbags, tote bags and clutches in Cameroon.',
    },
    {
      name: 'Accessories',
      description: 'Wig caps, edge brushes, styling tools and hair care',
      sortOrder: 3,
      isActive: true,
    },
  ];

  const categories = {};

  for (const cat of catData) {
    // FIX: filter by `name` (the actual unique index), not slug.
    // slug is generated by a pre('save') hook — it's not available for querying
    // until after the first save, so using it as a findOneAndUpdate filter
    // caused E11000 duplicate key errors on re-runs.
    let saved = await Category.findOne({ name: cat.name });
    if (saved) {
      // Update fields in case they changed
      Object.assign(saved, cat);
      await saved.save();
      console.log(`  ↷ Updated: ${cat.name}`);
    } else {
      saved = new Category(cat);
      await saved.save(); // pre('save') hook sets slug here
      console.log(`  ✓ Created: ${cat.name}`);
    }
    categories[cat.name] = saved._id;
  }

  // ── Demo user for reviews ──────────────────────────────────────────────────
  let demoUser = await User.findOne({ email: 'demo@nqcollection.com' });
  if (!demoUser) {
    demoUser = await User.create({
      name: 'Demo Customer',
      email: 'demo@nqcollection.com',
      password: 'Demo@123456',
      role: 'customer',
    });
  }

  // ── Products ────────────────────────────────────────────────────────────────
  console.log('\nSeeding products...');

  // NOTE: `featured` is used instead of `isNew` for the "new arrivals" flag
  // because `isNew` is a reserved Mongoose schema pathname that can break
  // internal document-state tracking. The Product model uses `isNewArrival`
  // or `tags` to flag new products instead.
  const products = [

    // ════════════════════════════════════════════════════════════
    // WIGS
    // ════════════════════════════════════════════════════════════
    {
      name: 'Silky Straight HD Lace Front Wig — 20 inch',
      shortDescription: 'Ultra-natural HD lace, silky straight, pre-plucked hairline',
      description: `Experience the most natural-looking hairline with our HD Lace Front Wig. The ultra-thin HD lace melts seamlessly into all skin tones.\n\n• Hair type: 100% premium synthetic (feels like human hair)\n• Lace type: HD transparent lace front\n• Length: 20 inches\n• Density: 180%\n• Cap size: Medium (adjustable straps)\n• Heat resistant up to 180°C\n• Pre-plucked with baby hairs`,
      category: categories['Wigs'],
      price: 45000, compareAtPrice: 65000, stock: 12,
      sku: 'WIG-HDSTR-20', brand: 'NQ Hair',
      isFeatured: true,
      tags: ['lace-front', 'straight', 'hd-lace', '20-inch', 'new-arrival'],
      images: [
        { url: img('1522337360032-2be4de10d561'), alt: 'Silky straight HD lace front wig 20 inch' },
        { url: img('1519699047748-de8e457a634e'), alt: 'Straight wig side view' },
      ],
      variants: [
        { label: 'Natural Black', sku: 'WIG-HDSTR-20-BLK', price: 45000, stock: 5 },
        { label: 'Dark Brown',    sku: 'WIG-HDSTR-20-DBR', price: 45000, stock: 4 },
        { label: 'Soft Black',    sku: 'WIG-HDSTR-20-SBL', price: 47000, stock: 3 },
      ],
      soldCount: 34,
      reviews: [
        { user: demoUser._id, name: 'Amina Fouda',    rating: 5, comment: 'Absolutely stunning! The lace is so thin and natural.' },
        { user: demoUser._id, name: 'Christelle Ngo', rating: 5, comment: 'Delivered to Douala in 2 days. So silky!' },
        { user: demoUser._id, name: 'Sandra Etame',   rating: 4, comment: 'Beautiful wig, fits perfectly.' },
      ],
    },

    {
      name: 'Body Wave Lace Front Wig — 22 inch',
      shortDescription: 'Gorgeous body wave pattern, bouncy and full',
      description: `Beautiful wave pattern adds volume and movement for any occasion.\n\n• Hair type: Premium heat-resistant fiber\n• Lace type: Transparent lace front (13×4)\n• Length: 22 inches\n• Density: 150%\n• Pre-plucked natural hairline\n• Adjustable cap — fits most head sizes`,
      category: categories['Wigs'],
      price: 52000, compareAtPrice: 75000, stock: 8,
      sku: 'WIG-BWAVE-22', brand: 'NQ Hair',
      isFeatured: true,
      tags: ['lace-front', 'body-wave', '22-inch', 'new-arrival'],
      images: [
        { url: img('1580618672591-eb180b1a44f6'), alt: 'Body wave lace front wig 22 inch' },
      ],
      variants: [
        { label: 'Natural Black', sku: 'WIG-BWAVE-22-BLK', price: 52000, stock: 3 },
        { label: 'Dark Brown #2', sku: 'WIG-BWAVE-22-DB2', price: 52000, stock: 3 },
        { label: 'Burgundy #99J', sku: 'WIG-BWAVE-22-BUR', price: 56000, stock: 2 },
      ],
      soldCount: 21,
      reviews: [
        { user: demoUser._id, name: 'Raissa Mbarga', rating: 5, comment: 'The waves are so bouncy and beautiful!' },
        { user: demoUser._id, name: 'Grace Biya',    rating: 4, comment: 'The burgundy colour is stunning in the sun.' },
      ],
    },

    {
      name: 'Deep Curly 4×4 Closure Wig — 18 inch',
      shortDescription: 'Defined deep curls, natural bounce and volume',
      description: `Beautiful deep curly closure wig with realistic parting space.\n\n• Hair type: Premium curl-resistant fiber\n• Closure: 4×4 lace closure\n• Length: 18 inches (stretched: 22 inches)\n• Density: 130%\n• Can be finger-combed for looser curls`,
      category: categories['Wigs'],
      price: 38000, compareAtPrice: 55000, stock: 15,
      sku: 'WIG-DCURL-18', brand: 'NQ Hair',
      isFeatured: false,
      tags: ['closure', 'curly', '18-inch', 'deep-curl', 'new-arrival'],
      images: [
        { url: img('1590540910836-58a18476a1e3'), alt: 'Deep curly closure wig 18 inch' },
      ],
      variants: [
        { label: 'Natural Black', sku: 'WIG-DCURL-18-BLK', price: 38000, stock: 8 },
        { label: 'Dark Brown',    sku: 'WIG-DCURL-18-DBR', price: 38000, stock: 4 },
        { label: 'Ombre T1B/30', sku: 'WIG-DCURL-18-OMB', price: 43000, stock: 3 },
      ],
      soldCount: 18,
      reviews: [
        { user: demoUser._id, name: 'Nadine Kom',    rating: 5, comment: 'The curls are so defined and beautiful!' },
        { user: demoUser._id, name: 'Laure Tchoupo', rating: 5, comment: 'Gorgeous wig. Stays perfect all week.' },
      ],
    },

    {
      name: 'Honey Blonde Straight Lace Front Wig — 24 inch',
      shortDescription: 'Gorgeous honey blonde colour, sleek and straight',
      description: `Stunning honey blonde lace front wig that flatters all skin tones.\n\n• Lace type: HD transparent lace front (13×6 wide part)\n• Length: 24 inches\n• Density: 180%\n• Colour: Honey Blonde (#27)\n• Pre-plucked with baby hairs\n• Heat resistant`,
      category: categories['Wigs'],
      price: 58000, compareAtPrice: 82000, stock: 6,
      sku: 'WIG-BLOND-24', brand: 'NQ Hair',
      isFeatured: true,
      tags: ['lace-front', 'blonde', 'straight', '24-inch', 'coloured'],
      images: [
        { url: img('1484863137850-bafb72e23e7c'), alt: 'Honey blonde straight lace front wig 24 inch' },
      ],
      variants: [
        { label: 'Honey Blonde #27',       sku: 'WIG-BLOND-24-H27',  price: 58000, stock: 3 },
        { label: 'Platinum Blonde #613',   sku: 'WIG-BLOND-24-P613', price: 62000, stock: 2 },
        { label: 'Ombre Black to Blonde',  sku: 'WIG-BLOND-24-OMB',  price: 65000, stock: 1 },
      ],
      soldCount: 15,
      reviews: [
        { user: demoUser._id, name: 'Carine Essama', rating: 5, comment: 'This blonde wig is EVERYTHING!' },
        { user: demoUser._id, name: 'Sandra Etame',  rating: 4, comment: 'Looks so natural with my skin tone.' },
      ],
    },

    {
      name: 'Short Bob Lace Front Wig — 12 inch',
      shortDescription: 'Chic and classy bob cut, perfect for everyday elegance',
      description: `Classic 12-inch lace front bob — effortlessly chic with minimal styling.\n\n• Lace type: Transparent lace front\n• Length: 12 inches (chin to shoulder length)\n• Density: 150%\n• Can be cut/styled by a stylist\n• Very lightweight and comfortable`,
      category: categories['Wigs'],
      price: 28000, compareAtPrice: 40000, stock: 20,
      sku: 'WIG-BOB-12', brand: 'NQ Hair',
      isFeatured: false,
      tags: ['bob', 'short', 'lace-front', '12-inch', 'everyday'],
      images: [
        { url: img('1529736576495-1518de573536'), alt: 'Short bob lace front wig 12 inch' },
      ],
      variants: [
        { label: 'Natural Black', sku: 'WIG-BOB-12-BLK', price: 28000, stock: 8 },
        { label: 'Dark Brown',    sku: 'WIG-BOB-12-DBR', price: 28000, stock: 7 },
        { label: 'Burgundy',      sku: 'WIG-BOB-12-BUR', price: 32000, stock: 5 },
      ],
      soldCount: 42,
      reviews: [
        { user: demoUser._id, name: 'Amina Fouda',    rating: 5, comment: 'My go-to everyday wig. So easy to style.' },
        { user: demoUser._id, name: 'Christelle Ngo', rating: 5, comment: 'Light, comfortable and so chic. I bought two!' },
        { user: demoUser._id, name: 'Grace Biya',     rating: 4, comment: 'Great quality for the price.' },
      ],
    },

    {
      name: 'Kinky Straight Full Lace Wig — 16 inch',
      shortDescription: 'Natural kinky texture, full lace for versatile styling',
      description: `Mimics natural African hair texture while being easy to maintain.\n\n• Lace type: Full lace (part anywhere)\n• Length: 16 inches\n• Density: 130%\n• Can wear in high ponytail or bun\n• Perfect for natural hair lovers`,
      category: categories['Wigs'],
      price: 42000, compareAtPrice: 60000, stock: 10,
      sku: 'WIG-KSTR-16', brand: 'NQ Hair',
      isFeatured: false,
      tags: ['full-lace', 'kinky-straight', '16-inch', 'natural', 'new-arrival'],
      images: [
        { url: img('1607990281689-377f4e6e8e11'), alt: 'Kinky straight full lace wig 16 inch' },
      ],
      variants: [
        { label: 'Natural Black 1B', sku: 'WIG-KSTR-16-1B', price: 42000, stock: 5 },
        { label: 'Off Black 2',      sku: 'WIG-KSTR-16-02', price: 42000, stock: 3 },
        { label: 'Dark Brown 4',     sku: 'WIG-KSTR-16-04', price: 44000, stock: 2 },
      ],
      soldCount: 9,
      reviews: [
        { user: demoUser._id, name: 'Raissa Mbarga', rating: 5, comment: 'Blends perfectly with my natural hair!' },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // BAGS
    // ════════════════════════════════════════════════════════════
    {
      name: 'Classic Structured Tote Bag — Black',
      shortDescription: 'Timeless black tote, gold hardware, fits everything',
      description: `Timeless tote that combines elegance with practicality.\n\n• Material: Premium vegan leather (PU)\n• Colour: Jet black with gold-tone hardware\n• Size: 40cm × 32cm × 15cm\n• Closure: Magnetic snap\n• Interior: 1 main compartment, 2 slip pockets, 1 zip pocket\n• Includes: Removable shoulder strap`,
      category: categories['Bags'],
      price: 35000, compareAtPrice: 50000, stock: 15,
      sku: 'BAG-TOTE-BLK', brand: 'NQ',
      isFeatured: true,
      tags: ['tote', 'black', 'everyday', 'office'],
      images: [
        { url: img('1548036161-65effc0c3b85'), alt: 'Classic structured black tote bag' },
      ],
      soldCount: 28,
      reviews: [
        { user: demoUser._id, name: 'Nadine Kom',    rating: 5, comment: 'Absolutely beautiful. Amazing leather quality.' },
        { user: demoUser._id, name: 'Grace Biya',    rating: 5, comment: 'I use it every day for work. Spacious and elegant.' },
        { user: demoUser._id, name: 'Laure Tchoupo', rating: 4, comment: 'The gold hardware looks very luxurious.' },
      ],
    },

    {
      name: 'Mini Quilted Crossbody Bag — Nude Beige',
      shortDescription: 'Chic quilted mini bag, adjustable chain strap',
      description: `Classic quilted pattern with delicate chain strap — designer-inspired look.\n\n• Material: Premium quilted PU leather\n• Colour: Nude beige with silver-tone chain\n• Size: 22cm × 16cm × 8cm\n• Strap: Adjustable chain (crossbody or clutch)\n• Closure: Zip-top`,
      category: categories['Bags'],
      price: 22000, compareAtPrice: 35000, stock: 18,
      sku: 'BAG-MINI-NUDE', brand: 'NQ',
      isFeatured: true,
      tags: ['crossbody', 'mini', 'quilted', 'new-arrival'],
      images: [
        { url: img('1584917865442-de6978d2f4cf'), alt: 'Mini quilted crossbody bag nude beige' },
      ],
      variants: [
        { label: 'Nude Beige', sku: 'BAG-MINI-NUDE', price: 22000, stock: 7 },
        { label: 'Black',      sku: 'BAG-MINI-BLK',  price: 22000, stock: 6 },
        { label: 'Dusty Pink', sku: 'BAG-MINI-PINK', price: 22000, stock: 5 },
      ],
      soldCount: 35,
      reviews: [
        { user: demoUser._id, name: 'Carine Essama', rating: 5, comment: 'So cute! Perfect size for going out.' },
        { user: demoUser._id, name: 'Sandra Etame',  rating: 5, comment: 'The chain is sturdy and beautiful.' },
      ],
    },

    {
      name: 'Executive Leather Shoulder Bag — Brown',
      shortDescription: 'Professional structured shoulder bag, rich cognac brown',
      description: `Sophisticated executive shoulder bag — perfect for work and events.\n\n• Material: Premium structured PU leather\n• Colour: Rich cognac brown with gold hardware\n• Size: 38cm × 28cm × 12cm\n• Closure: Double zip\n• Interior: 2 main compartments, 4 card slots, 1 zip pocket`,
      category: categories['Bags'],
      price: 42000, compareAtPrice: 62000, stock: 10,
      sku: 'BAG-EXEC-BRN', brand: 'NQ',
      isFeatured: false,
      tags: ['shoulder-bag', 'brown', 'office', 'professional'],
      images: [
        { url: img('1553062407-98eeb64c6a62'), alt: 'Executive brown leather shoulder bag' },
      ],
      soldCount: 16,
      reviews: [
        { user: demoUser._id, name: 'Amina Fouda', rating: 5, comment: 'Such a classy bag! I carry it to work every day.' },
      ],
    },

    {
      name: 'Velvet Evening Clutch — Emerald Green',
      shortDescription: 'Luxurious velvet clutch, perfect for special occasions',
      description: `Rich emerald green velvet clutch — the perfect finishing touch for any occasion.\n\n• Material: Rich velvet fabric with gold-tone frame\n• Colour: Emerald green\n• Size: 28cm × 14cm × 5cm\n• Closure: Gold clasp frame\n• Strap: Removable gold chain (40cm)\n• Perfect for: Weddings, parties, galas, graduation`,
      category: categories['Bags'],
      price: 16000, compareAtPrice: 25000, stock: 20,
      sku: 'BAG-VELVET-GRN', brand: 'NQ',
      isFeatured: false,
      tags: ['clutch', 'velvet', 'evening', 'occasion', 'new-arrival'],
      images: [
        { url: img('1548036161-65effc0c3b85'), alt: 'Emerald green velvet evening clutch' },
      ],
      variants: [
        { label: 'Emerald Green', sku: 'BAG-VELVET-GRN', price: 16000, stock: 7 },
        { label: 'Burgundy Red',  sku: 'BAG-VELVET-RED', price: 16000, stock: 7 },
        { label: 'Midnight Blue', sku: 'BAG-VELVET-BLU', price: 16000, stock: 6 },
      ],
      soldCount: 22,
      reviews: [
        { user: demoUser._id, name: 'Nadine Kom',    rating: 5, comment: 'Everyone at the wedding asked where I got it!' },
        { user: demoUser._id, name: 'Laure Tchoupo', rating: 5, comment: 'The velvet is so rich and beautiful.' },
      ],
    },

    // ════════════════════════════════════════════════════════════
    // ACCESSORIES
    // ════════════════════════════════════════════════════════════
    {
      name: 'Wig Installation Kit — Complete Set',
      shortDescription: 'Everything you need for a flawless wig install',
      description: `Professional wig install at home. Includes:\n\n• 1× Wig cap (nude, one size fits all)\n• 1× Edge control gel (60ml)\n• 1× Edge brush + comb combo\n• 1× Wig glue stick (skin-safe)\n• 1× Lace tint spray (medium brown)\n• 1× Satin hair bonnet\n• 1× Fine-tooth tail comb`,
      category: categories['Accessories'],
      price: 12000, compareAtPrice: 18000, stock: 30,
      sku: 'ACC-WIGKIT-001', brand: 'NQ Care',
      isFeatured: false,
      tags: ['accessories', 'wig-kit', 'installation', 'new-arrival'],
      images: [
        { url: img('1522337360032-2be4de10d900'), alt: 'Complete wig installation kit' },
      ],
      soldCount: 47,
      reviews: [
        { user: demoUser._id, name: 'Carine Essama', rating: 5, comment: 'Lifesaver! The edge gel and lace tint spray are perfect.' },
        { user: demoUser._id, name: 'Grace Biya',    rating: 4, comment: 'Good value for money. Everything in one package.' },
      ],
    },

    {
      name: 'Satin Bonnet — Extra Large',
      shortDescription: 'Protects your wig and natural hair overnight',
      description: `Extra-large satin bonnet that fits comfortably over any wig length.\n\n• Material: 100% satin\n• Size: XL — fits all hair lengths and wig sizes\n• Wide, soft elastic — doesn't leave marks\n• Machine washable\n• Also great for natural hair, braids and twists`,
      category: categories['Accessories'],
      price: 3500, compareAtPrice: 5500, stock: 50,
      sku: 'ACC-BONNET-XL', brand: 'NQ Care',
      isFeatured: false,
      tags: ['accessories', 'bonnet', 'satin', 'hair-care'],
      images: [
        { url: img('1522337360032-2be4de10d800'), alt: 'Extra large satin bonnet' },
      ],
      variants: [
        { label: 'Black',      sku: 'ACC-BONNET-BLK',  price: 3500, stock: 20 },
        { label: 'Nude Beige', sku: 'ACC-BONNET-NUDE', price: 3500, stock: 15 },
        { label: 'Pink',       sku: 'ACC-BONNET-PNK',  price: 3500, stock: 15 },
      ],
      soldCount: 63,
      reviews: [
        { user: demoUser._id, name: 'Amina Fouda', rating: 5, comment: 'My wigs last so much longer since I started using this.' },
      ],
    },

  ];

  // ── Insert products ──────────────────────────────────────────────────────────
  let inserted = 0;
  let skipped  = 0;

  for (const productData of products) {
    const exists = await Product.findOne({ sku: productData.sku });
    if (exists) {
      console.log(`  ↷ Skipped (exists): ${productData.name}`);
      skipped++;
      continue;
    }

    const reviews    = productData.reviews || [];
    const rating     = reviews.length
      ? reviews.reduce((s, r) => s + r.rating, 0) / reviews.length
      : 0;

    const product = new Product({
      ...productData,
      rating,
      numReviews: reviews.length,
    });

    await product.save();
    console.log(`  ✓ ${product.name}`);
    inserted++;
  }

  console.log(`\n✅ Seed complete!`);
  console.log(`   ${inserted} products inserted`);
  console.log(`   ${skipped} products skipped (already existed)`);
  console.log(`   ${Object.keys(categories).length} categories ready\n`);

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch(err => {
  console.error('\n❌ Seed failed:', err.message);
  console.error(err);
  process.exit(1);
});
